# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: zephyr-gtest-app
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: google
      url-base: https://github.com/google

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import:
        name-allowlist:
          - cmsis
          - segger
          - hal_nordic
    - name: googletest
      remote: google
      repo-path: googletest
      revision: e235eb34c6c4fed790ccdad4b16394301360dcd4
      path: zephyr-gtest-app/googletest/googletest